# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-26 02:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0012_auto_20170125_0535'),
        ('enterprise', '0013_auto_20170125_1157'),
    ]

    operations = [
    ]
