# Generated by Django 3.2.15 on 2023-07-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0154_alter_systemwideenterpriseuserroleassignment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisecustomer',
            name='hide_course_price_when_zero',
            field=models.BooleanField(default=False, help_text='Specify whether course cost should be hidden in the landing page when the final price is zero.'),
        ),
        migrations.AddField(
            model_name='historicalenterprisecustomer',
            name='hide_course_price_when_zero',
            field=models.BooleanField(default=False, help_text='Specify whether course cost should be hidden in the landing page when the final price is zero.'),
        ),
    ]
