# Generated by Django 3.2.21 on 2024-12-02 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0172_adds_allow_enrollment_in_invite_only_courses_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterprisecustomer',
            name='hide_course_price_when_zero',
        ),
        migrations.RemoveField(
            model_name='historicalenterprisecustomer',
            name='hide_course_price_when_zero',
        ),
    ]
