# Generated by Django 5.2.11 on 2026-02-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0241_alter_defaultenterpriseenrollmentintention_realized_enrollments'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisecustomer',
            name='allow_enrollment_in_invite_only_courses',
            field=models.BooleanField(default=False, help_text="Specifies if learners are allowed to enroll into courses marked as 'invitation-only', when they attempt to enroll from the landing page."),
        ),
        migrations.AddField(
            model_name='historicalenterprisecustomer',
            name='allow_enrollment_in_invite_only_courses',
            field=models.BooleanField(default=False, help_text="Specifies if learners are allowed to enroll into courses marked as 'invitation-only', when they attempt to enroll from the landing page."),
        ),
    ]
