# Generated by Django 3.2.12 on 2023-09-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xapi', '0007_auto_20220405_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='xapilrsconfiguration',
            name='auth_method',
            field=models.CharField(choices=[('BASIC', 'HTTP Basic'), ('OAUTH2_CC', 'OAuth 2.0 Client Credentials')], default='BASIC', help_text='The Authentication Method to use when sending the xAPI data to the endpoint.', max_length=16, verbose_name='xAPI POST Authentication Method'),
        ),
        migrations.AddField(
            model_name='xapilrsconfiguration',
            name='auth_url',
            field=models.URLField(blank=True, help_text='URL to use for authentication. Eg., Token URL for OAuth', null=True),
        ),
        migrations.AddField(
            model_name='xapilrsconfiguration',
            name='oauth_scope',
            field=models.CharField(blank=True, help_text='The "scope" to pass for OAuth authentication.', max_length=255, null=True, verbose_name='OAuth scope'),
        ),
    ]
