# Generated by Django 3.2.12 on 2023-09-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xapi', '0008_adds_auth_method_scope_and_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='xapilrsconfiguration',
            name='plain_course_id_in_statements',
            field=models.BooleanField(default=False, help_text='Uses the plain course ID (eg., course-v1:X+Y+Z) instead of the URI format in xAPI statements.', verbose_name='Use plain Course ID in xAPI Statements'),
        ),
    ]
